version: "3.9"

services:
  app:
    # depends_on:
    #   - sqlserver
    build:
      context: .
      target: development
    command:
    volumes:
      - .:/src
      - ~/.aspnet/https:/https:ro
  # sqlserver:
  #   image: mcr.microsoft.com/azure-sql-edge
  #   volumes:
  #     - sql:/var/opt/mssql
  #   environment:
  #     - "ACCEPT_EULA=Y"
  #     - "MSSQL_SA_PASSWORD=p@ssw0rd"
  #   user: root

  # volumes:
  #   sql:
